### ISSUE TITLE
HMC8012 “crashes” when launching the example code more than once.

### ISSUE THREAD

**Issue by Vincent-Stragier** [Rohde-Schwarz/Examples#7]
Hi,

In #6, I noticed that the HMC8012 was crashing when trying to launch the example script more than once. The crash either lock the sampling (count stuck at 0) or impeach the remote host to create a log file internally.

Is there something missing in the script to properly reset the device (other than `hmc8012 = RsInstrument(resource, reset=True, [...])` and `hmc8012.clear_status()`)?

The workaround from now on is to manually restart the multimeter.

Best,
Vincent

P.S.: if `hmc8012 = RsInstrument(resource, reset=True, [...])` is equivalent to calling `hmc8012.reset()`, why do we also call  `hmc8012.clear_status()` (which is called in `hmc8012.reset()`)?

**Comment by Miloslav-RS** [comment]
Unfortunately, the HMC8012 is a discontinued product, there will be no FW updates that can fix this issue...
