### ISSUE TITLE
Running RsInstrument_NGE_U-I-P-request.py code gives error

### ISSUE THREAD

**Issue by Abhiyong** [Rohde-Schwarz/Examples#8]
Running RsInstrument_NGE_U-I-P-request.py code gives below error:

![image](https://user-images.githubusercontent.com/126080089/223027101-4897fa8d-4fd3-4d1f-9bd1-5dbe7b27fca7.png)

How to solve it?

**Comment by Miloslav-RS** [comment]
Sorry for the delay, this is a strange behaviour, pointing to the instrument's session loss. Is this reproducable with FW 1.57?
